### ISSUE TITLE
Untamed non-albino rats not spawning.

### ISSUE THREAD

**Issue by deadspidervenom** [AlexModGuy/Rats#162] opened 2020-01-19 08:34 UTC
If you have "Rats Spawn Like Monsters" almost no non-tamed rats will spawn, to the point where you can't get a pet. This includes on garbage piles.

**Comment by GizmoTheMoonPig** [comment] 2022-12-27 15:26
this sounds like some sort of mod conflict. You can only get albino rats from breeding. Closing as im not able to reproduce

**Closed by GizmoTheMoonPig** 2022-12-27 15:26 UTC
Labels: 1.12.2
