### ISSUE TITLE
Cant tame rats 

### ISSUE THREAD

**Issue by Platipucat** [AlexModGuy/Rats#136] opened 2019-11-19 08:12 UTC
I can't tame rat no matter how many times I give it cheese 
Also rat seems to be completely resistant to damege except fire damage
I can provide additional information if you need

**Comment by Alex-the-666** [comment] 2019-11-21 05:40
what version are you using? do you get a game message from the rat when you try and tame it?

**Comment by Platipucat** [comment] 2019-11-21 18:10
> what version are you using? do you get a game message from the rat when you try and tame it?

I updated my modpack to 3.2.2
Taming rats in seem to work in single player
I would test taming on the server 
Rats are still immune to damage on the server

**Comment by OmegaJak** [comment] 2020-01-04 05:02
Using rats v3.2.4 on minecraft 1.12 on a small server with some friends, I encountered this same thing.

One of my friends is unable to tame any rats. We spawned some using a spawn egg to test and verify. When he fed the rat cheese, nothing at all happens. No message about not being able to tame, no log in the server console, no particle effects.

When I tried feeding the rat, everything worked as expected. I got the particles and eventually tamed the rat. The differences I see between me and my friend: I created the server and was the first user to sign in to it, and I was opped, he originally wasn't. I then opped him and that made no difference. We have not been able to get any rats to tame for him.

**Comment by OmegaJak** [comment] 2020-01-04 22:59
My apologies! This was (ironically) actually caused by my mod, Power Drop. I've created an issue on my mod to log the problem: https://github.com/OmegaJak/Power_Drop/issues/2.

After using vanilla dropping mechanics, my friend was able to tame rats just fine.

**Comment by Alzarath** [comment] 2020-03-04 19:57
I've also had this issue in the [MC.Eternal mod pack](https://www.curseforge.com/minecraft/modpacks/minecraft-eternal) (Rats v3.2.6). I can confirm that the first player to enter a server after the server starts is able to tame a rat (I was able to tame it before the restart, then restarted and the other first person to join could tame rats).

**Comment by gazpachoking** [comment] 2020-03-07 05:40
I was having a problem taming rats, but I found you cannot drop items from your inventory, you must set up a keybind for drop, and drop it from your hotbar with that key.

**Comment by GizmoTheMoonPig** [comment] 2023-04-04 13:50
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e

**Closed by GizmoTheMoonPig** 2023-04-04 13:50 UTC
Labels: bug, fixed in dev
