### ISSUE TITLE
[Suggest] Rats Farming Compatibility with Agricraft!

### ISSUE THREAD

**Issue by Bluepugs** [AlexModGuy/Rats#187] opened 2020-02-29 08:00 UTC
As of right now, rats won't farm anything that's on growing sticks from the mod Agricraft. Would be really neat if you could include this!

**Comment by Tenchu98** [comment] 2020-10-12 21:14
I second this idea, especially since I am making an all magic and rpg modpack.

**Comment by GizmoTheMoonPig** [comment] 2022-12-27 15:27
duplicate of #21

**Closed by GizmoTheMoonPig** 2022-12-27 15:27 UTC
Labels: 1.12.2
